# Generate with: vhs demo.tape

Output docs/assets/demo.gif

Set Shell "zsh"
Set FontSize 14
Set Width 1200
Set Height 700
Set Theme "Catppuccin Macchiato"

Sleep 1s
Type "pi"
Enter
Sleep 2s
Type "/fusion"
Enter
Sleep 2s
Type " "
Sleep 1s
Down 1
Type " "
Sleep 3.5s
Down 9
Sleep 500ms
Enter
Sleep 2.5s
Type "Go read "
Sleep 500ms
Type "@"
Sleep 500ms
Type "~"
Sleep 500ms
Type "/dot"
Sleep 500ms
Type "files/"
Sleep 1s
Type " and roast the"
Sleep 0.5s
Type "m in the style of a ciceronian "
Sleep 1s
Type "oration"
Sleep 500ms
Type ", in the "
Sleep 500ms
Type "English language."
Enter
Sleep 100s
